import sublime_plugin
import sublime

# The following 2 lines can be generated with "grunt sublime" in the main uikit code
uikit_classes = ["uk-link", "uk-img-preserve", "uk-h1", "uk-h2", "uk-h3", "uk-h4", "uk-h5", "uk-h6", "uk-grid", "uk-grid-margin", "uk-panel", "uk-grid-collapse", "uk-grid-small", "uk-grid-medium", "uk-grid-divider", "uk-width-1-1", "uk-width-medium-1-1", "uk-width-large-1-1", "uk-grid-match", "uk-grid-width-1-2", "uk-grid-width-1-3",
    "uk-grid-width-1-4", "uk-grid-width-1-5", "uk-grid-width-1-6", "uk-grid-width-1-10", "uk-grid-width-small-1-2", "uk-grid-width-small-1-3", "uk-grid-width-small-1-4", "uk-grid-width-small-1-5", "uk-grid-width-small-1-6", "uk-grid-width-small-1-10", "uk-grid-width-medium-1-2", "uk-grid-width-medium-1-3", "uk-grid-width-medium-1-4", "uk-grid-width-medium-1-5", "uk-grid-width-medium-1-6", "uk-grid-width-medium-1-10", "uk-grid-width-large-1-2", "uk-grid-width-large-1-3", "uk-grid-width-large-1-4", "uk-grid-width-large-1-5",
    "uk-grid-width-large-1-6", "uk-grid-width-large-1-10", "uk-grid-width-xlarge-1-2", "uk-grid-width-xlarge-1-3", "uk-grid-width-xlarge-1-4", "uk-grid-width-xlarge-1-5", "uk-grid-width-xlarge-1-6", "uk-grid-width-xlarge-1-10", "uk-width-1-2", "uk-width-2-4", "uk-width-3-6", "uk-width-5-10", "uk-width-1-3", "uk-width-2-6", "uk-width-2-3", "uk-width-4-6", "uk-width-1-4", "uk-width-3-4", "uk-width-1-5", "uk-width-2-10",
    "uk-width-2-5", "uk-width-4-10", "uk-width-3-5", "uk-width-6-10", "uk-width-4-5", "uk-width-8-10", "uk-width-1-6", "uk-width-5-6", "uk-width-1-10", "uk-width-3-10", "uk-width-7-10", "uk-width-9-10", "uk-width-small-1-1", "uk-width-small-1-2", "uk-width-small-2-4", "uk-width-small-3-6", "uk-width-small-5-10", "uk-width-small-1-3", "uk-width-small-2-6", "uk-width-small-2-3",
    "uk-width-small-4-6", "uk-width-small-1-4", "uk-width-small-3-4", "uk-width-small-1-5", "uk-width-small-2-10", "uk-width-small-2-5", "uk-width-small-4-10", "uk-width-small-3-5", "uk-width-small-6-10", "uk-width-small-4-5", "uk-width-small-8-10", "uk-width-small-1-6", "uk-width-small-5-6", "uk-width-small-1-10", "uk-width-small-3-10", "uk-width-small-7-10", "uk-width-small-9-10", "uk-width-medium-1-2", "uk-width-medium-2-4", "uk-width-medium-3-6",
    "uk-width-medium-5-10", "uk-width-medium-1-3", "uk-width-medium-2-6", "uk-width-medium-2-3", "uk-width-medium-4-6", "uk-width-medium-1-4", "uk-width-medium-3-4", "uk-width-medium-1-5", "uk-width-medium-2-10", "uk-width-medium-2-5", "uk-width-medium-4-10", "uk-width-medium-3-5", "uk-width-medium-6-10", "uk-width-medium-4-5", "uk-width-medium-8-10", "uk-width-medium-1-6", "uk-width-medium-5-6", "uk-width-medium-1-10", "uk-width-medium-3-10", "uk-width-medium-7-10",
    "uk-width-medium-9-10", "uk-width-large-1-2", "uk-width-large-2-4", "uk-width-large-3-6", "uk-width-large-5-10", "uk-width-large-1-3", "uk-width-large-2-6", "uk-width-large-2-3", "uk-width-large-4-6", "uk-width-large-1-4", "uk-width-large-3-4", "uk-width-large-1-5", "uk-width-large-2-10", "uk-width-large-2-5", "uk-width-large-4-10", "uk-width-large-3-5", "uk-width-large-6-10", "uk-width-large-4-5", "uk-width-large-8-10", "uk-width-large-1-6",
    "uk-width-large-5-6", "uk-width-large-1-10", "uk-width-large-3-10", "uk-width-large-7-10", "uk-width-large-9-10", "uk-push-1-2", "uk-push-2-4", "uk-push-3-6", "uk-push-5-10", "uk-push-1-3", "uk-push-2-6", "uk-push-2-3", "uk-push-4-6", "uk-push-1-4", "uk-push-3-4", "uk-push-1-5", "uk-push-2-10", "uk-push-2-5", "uk-push-4-10", "uk-push-3-5",
    "uk-push-6-10", "uk-push-4-5", "uk-push-8-10", "uk-push-1-6", "uk-push-5-6", "uk-push-1-10", "uk-push-3-10", "uk-push-7-10", "uk-push-9-10", "uk-pull-1-2", "uk-pull-2-4", "uk-pull-3-6", "uk-pull-5-10", "uk-pull-1-3", "uk-pull-2-6", "uk-pull-2-3", "uk-pull-4-6", "uk-pull-1-4", "uk-pull-3-4", "uk-pull-1-5",
    "uk-pull-2-10", "uk-pull-2-5", "uk-pull-4-10", "uk-pull-3-5", "uk-pull-6-10", "uk-pull-4-5", "uk-pull-8-10", "uk-pull-1-6", "uk-pull-5-6", "uk-pull-1-10", "uk-pull-3-10", "uk-pull-7-10", "uk-pull-9-10", "uk-panel-title", "uk-panel-badge", "uk-panel-teaser", "uk-panel-box", "uk-panel-box-hover", "uk-nav-side", "uk-panel-box-primary",
    "uk-panel-box-primary-hover", "uk-panel-box-secondary", "uk-panel-box-secondary-hover", "uk-panel-hover", "uk-panel-header", "uk-panel-space", "uk-panel-divider", "uk-article", "uk-article-title", "uk-article-meta", "uk-article-lead", "uk-article-divider", "uk-comment-header", "uk-comment-avatar", "uk-comment-title", "uk-comment-meta", "uk-comment-body", "uk-comment-list", "uk-comment", "uk-comment-primary",
    "uk-cover-background", "uk-cover", "uk-cover-object", "uk-nav", "uk-nav-header", "uk-nav-divider", "uk-nav-sub", "uk-nav-parent-icon", "uk-parent", "uk-open", "uk-active", "uk-nav-dropdown", "uk-nav-navbar", "uk-nav-offcanvas", "uk-touch", "uk-navbar", "uk-navbar-nav", "uk-navbar-nav-subtitle", "uk-navbar-brand", "uk-navbar-content",
    "uk-navbar-toggle", "uk-navbar-center", "uk-navbar-toggle-alt", "uk-navbar-flip", "uk-navbar-attached", "uk-subnav", "uk-subnav-line", "uk-subnav-pill", "uk-disabled", "uk-breadcrumb", "uk-pagination", "uk-pagination-previous", "uk-pagination-next", "uk-pagination-left", "uk-pagination-right", "uk-tab", "uk-tab-flip", "uk-tab-responsive", "uk-tab-center", "uk-tab-center-bottom",
    "uk-tab-bottom", "uk-tab-grid", "uk-tab-left", "uk-tab-right", "uk-thumbnav", "uk-list", "uk-list-line", "uk-list-striped", "uk-list-space", "uk-description-list-horizontal", "uk-description-list-line", "uk-table", "uk-table-middle", "uk-table-striped", "uk-table-condensed", "uk-table-hover", "uk-form", "uk-form-small", "uk-form-large", "uk-form-danger",
    "uk-form-success", "uk-form-blank", "uk-form-width-mini", "uk-form-width-small", "uk-form-width-medium", "uk-form-width-large", "uk-form-row", "uk-form-help-inline", "uk-form-help-block", "uk-form-controls", "uk-form-controls-condensed", "uk-form-stacked", "uk-form-label", "uk-form-horizontal", "uk-form-controls-text", "uk-form-icon", "uk-form-icon-flip", "uk-button", "uk-button-primary", "uk-button-success",
    "uk-button-danger", "uk-button-link", "uk-button-mini", "uk-button-small", "uk-button-large", "uk-button-group", "uk-button-dropdown", "uk-icon-small", "uk-icon-medium", "uk-icon-large", "uk-icon-spin", "uk-icon-hover", "uk-icon-button", "uk-icon-glass", "uk-icon-music", "uk-icon-search", "uk-icon-envelope-o", "uk-icon-heart", "uk-icon-star", "uk-icon-star-o",
    "uk-icon-user", "uk-icon-film", "uk-icon-th-large", "uk-icon-th", "uk-icon-th-list", "uk-icon-check", "uk-icon-close", "uk-icon-remove", "uk-icon-times", "uk-icon-search-plus", "uk-icon-search-minus", "uk-icon-power-off", "uk-icon-signal", "uk-icon-cog", "uk-icon-gear", "uk-icon-trash-o", "uk-icon-home", "uk-icon-file-o", "uk-icon-clock-o", "uk-icon-road",
    "uk-icon-download", "uk-icon-arrow-circle-o-down", "uk-icon-arrow-circle-o-up", "uk-icon-inbox", "uk-icon-play-circle-o", "uk-icon-repeat", "uk-icon-rotate-right", "uk-icon-refresh", "uk-icon-list-alt", "uk-icon-lock", "uk-icon-flag", "uk-icon-headphones", "uk-icon-volume-off", "uk-icon-volume-down", "uk-icon-volume-up", "uk-icon-qrcode", "uk-icon-barcode", "uk-icon-tag", "uk-icon-tags", "uk-icon-book",
    "uk-icon-bookmark", "uk-icon-print", "uk-icon-camera", "uk-icon-font", "uk-icon-bold", "uk-icon-italic", "uk-icon-text-height", "uk-icon-text-width", "uk-icon-align-left", "uk-icon-align-center", "uk-icon-align-right", "uk-icon-align-justify", "uk-icon-list", "uk-icon-dedent", "uk-icon-outdent", "uk-icon-indent", "uk-icon-video-camera", "uk-icon-image", "uk-icon-photo", "uk-icon-picture-o",
    "uk-icon-pencil", "uk-icon-map-marker", "uk-icon-adjust", "uk-icon-tint", "uk-icon-edit", "uk-icon-pencil-square-o", "uk-icon-share-square-o", "uk-icon-check-square-o", "uk-icon-arrows", "uk-icon-step-backward", "uk-icon-fast-backward", "uk-icon-backward", "uk-icon-play", "uk-icon-pause", "uk-icon-stop", "uk-icon-forward", "uk-icon-fast-forward", "uk-icon-step-forward", "uk-icon-eject", "uk-icon-chevron-left",
    "uk-icon-chevron-right", "uk-icon-plus-circle", "uk-icon-minus-circle", "uk-icon-times-circle", "uk-icon-check-circle", "uk-icon-question-circle", "uk-icon-info-circle", "uk-icon-crosshairs", "uk-icon-times-circle-o", "uk-icon-check-circle-o", "uk-icon-ban", "uk-icon-arrow-left", "uk-icon-arrow-right", "uk-icon-arrow-up", "uk-icon-arrow-down", "uk-icon-mail-forward", "uk-icon-share", "uk-icon-expand", "uk-icon-compress", "uk-icon-plus",
    "uk-icon-minus", "uk-icon-asterisk", "uk-icon-exclamation-circle", "uk-icon-gift", "uk-icon-leaf", "uk-icon-fire", "uk-icon-eye", "uk-icon-eye-slash", "uk-icon-exclamation-triangle", "uk-icon-warning", "uk-icon-plane", "uk-icon-calendar", "uk-icon-random", "uk-icon-comment", "uk-icon-magnet", "uk-icon-chevron-up", "uk-icon-chevron-down", "uk-icon-retweet", "uk-icon-shopping-cart", "uk-icon-folder",
    "uk-icon-folder-open", "uk-icon-arrows-v", "uk-icon-arrows-h", "uk-icon-bar-chart-o", "uk-icon-bar-chart", "uk-icon-twitter-square", "uk-icon-facebook-square", "uk-icon-camera-retro", "uk-icon-key", "uk-icon-cogs", "uk-icon-gears", "uk-icon-comments", "uk-icon-thumbs-o-up", "uk-icon-thumbs-o-down", "uk-icon-star-half", "uk-icon-heart-o", "uk-icon-sign-out", "uk-icon-linkedin-square", "uk-icon-thumb-tack", "uk-icon-external-link",
    "uk-icon-sign-in", "uk-icon-trophy", "uk-icon-github-square", "uk-icon-upload", "uk-icon-lemon-o", "uk-icon-phone", "uk-icon-square-o", "uk-icon-bookmark-o", "uk-icon-phone-square", "uk-icon-twitter", "uk-icon-facebook-f", "uk-icon-facebook", "uk-icon-github", "uk-icon-unlock", "uk-icon-credit-card", "uk-icon-rss", "uk-icon-hdd-o", "uk-icon-bullhorn", "uk-icon-bell", "uk-icon-certificate",
    "uk-icon-hand-o-right", "uk-icon-hand-o-left", "uk-icon-hand-o-up", "uk-icon-hand-o-down", "uk-icon-arrow-circle-left", "uk-icon-arrow-circle-right", "uk-icon-arrow-circle-up", "uk-icon-arrow-circle-down", "uk-icon-globe", "uk-icon-wrench", "uk-icon-tasks", "uk-icon-filter", "uk-icon-briefcase", "uk-icon-arrows-alt", "uk-icon-group", "uk-icon-users", "uk-icon-chain", "uk-icon-link", "uk-icon-cloud", "uk-icon-flask",
    "uk-icon-cut", "uk-icon-scissors", "uk-icon-copy", "uk-icon-files-o", "uk-icon-paperclip", "uk-icon-floppy-o", "uk-icon-save", "uk-icon-square", "uk-icon-bars", "uk-icon-navicon", "uk-icon-reorder", "uk-icon-list-ul", "uk-icon-list-ol", "uk-icon-strikethrough", "uk-icon-underline", "uk-icon-table", "uk-icon-magic", "uk-icon-truck", "uk-icon-pinterest", "uk-icon-pinterest-square",
    "uk-icon-google-plus-square", "uk-icon-google-plus", "uk-icon-money", "uk-icon-caret-down", "uk-icon-caret-up", "uk-icon-caret-left", "uk-icon-caret-right", "uk-icon-columns", "uk-icon-sort", "uk-icon-unsorted", "uk-icon-sort-desc", "uk-icon-sort-down", "uk-icon-sort-asc", "uk-icon-sort-up", "uk-icon-envelope", "uk-icon-linkedin", "uk-icon-rotate-left", "uk-icon-undo", "uk-icon-gavel", "uk-icon-legal",
    "uk-icon-dashboard", "uk-icon-tachometer", "uk-icon-comment-o", "uk-icon-comments-o", "uk-icon-bolt", "uk-icon-flash", "uk-icon-sitemap", "uk-icon-umbrella", "uk-icon-clipboard", "uk-icon-paste", "uk-icon-lightbulb-o", "uk-icon-exchange", "uk-icon-cloud-download", "uk-icon-cloud-upload", "uk-icon-user-md", "uk-icon-stethoscope", "uk-icon-suitcase", "uk-icon-bell-o", "uk-icon-coffee", "uk-icon-cutlery",
    "uk-icon-file-text-o", "uk-icon-building-o", "uk-icon-hospital-o", "uk-icon-ambulance", "uk-icon-medkit", "uk-icon-fighter-jet", "uk-icon-beer", "uk-icon-h-square", "uk-icon-plus-square", "uk-icon-angle-double-left", "uk-icon-angle-double-right", "uk-icon-angle-double-up", "uk-icon-angle-double-down", "uk-icon-angle-left", "uk-icon-angle-right", "uk-icon-angle-up", "uk-icon-angle-down", "uk-icon-desktop", "uk-icon-laptop", "uk-icon-tablet",
    "uk-icon-mobile-phone", "uk-icon-mobile", "uk-icon-circle-o", "uk-icon-quote-left", "uk-icon-quote-right", "uk-icon-spinner", "uk-icon-circle", "uk-icon-mail-reply", "uk-icon-reply", "uk-icon-github-alt", "uk-icon-folder-o", "uk-icon-folder-open-o", "uk-icon-smile-o", "uk-icon-frown-o", "uk-icon-meh-o", "uk-icon-gamepad", "uk-icon-keyboard-o", "uk-icon-flag-o", "uk-icon-flag-checkered", "uk-icon-terminal",
    "uk-icon-code", "uk-icon-mail-reply-all", "uk-icon-reply-all", "uk-icon-star-half-empty", "uk-icon-star-half-full", "uk-icon-star-half-o", "uk-icon-location-arrow", "uk-icon-crop", "uk-icon-code-fork", "uk-icon-chain-broken", "uk-icon-unlink", "uk-icon-question", "uk-icon-info", "uk-icon-exclamation", "uk-icon-superscript", "uk-icon-subscript", "uk-icon-eraser", "uk-icon-puzzle-piece", "uk-icon-microphone", "uk-icon-microphone-slash",
    "uk-icon-shield", "uk-icon-calendar-o", "uk-icon-fire-extinguisher", "uk-icon-rocket", "uk-icon-maxcdn", "uk-icon-chevron-circle-left", "uk-icon-chevron-circle-right", "uk-icon-chevron-circle-up", "uk-icon-chevron-circle-down", "uk-icon-html5", "uk-icon-css3", "uk-icon-anchor", "uk-icon-unlock-alt", "uk-icon-bullseye", "uk-icon-ellipsis-h", "uk-icon-ellipsis-v", "uk-icon-rss-square", "uk-icon-play-circle", "uk-icon-ticket", "uk-icon-minus-square",
    "uk-icon-minus-square-o", "uk-icon-level-up", "uk-icon-level-down", "uk-icon-check-square", "uk-icon-pencil-square", "uk-icon-external-link-square", "uk-icon-share-square", "uk-icon-compass", "uk-icon-caret-square-o-down", "uk-icon-toggle-down", "uk-icon-caret-square-o-up", "uk-icon-toggle-up", "uk-icon-caret-square-o-right", "uk-icon-toggle-right", "uk-icon-eur", "uk-icon-euro", "uk-icon-gbp", "uk-icon-dollar", "uk-icon-usd", "uk-icon-inr",
    "uk-icon-rupee", "uk-icon-cny", "uk-icon-jpy", "uk-icon-rmb", "uk-icon-yen", "uk-icon-rouble", "uk-icon-rub", "uk-icon-ruble", "uk-icon-krw", "uk-icon-won", "uk-icon-bitcoin", "uk-icon-btc", "uk-icon-file", "uk-icon-file-text", "uk-icon-sort-alpha-asc", "uk-icon-sort-alpha-desc", "uk-icon-sort-amount-asc", "uk-icon-sort-amount-desc", "uk-icon-sort-numeric-asc", "uk-icon-sort-numeric-desc",
    "uk-icon-thumbs-up", "uk-icon-thumbs-down", "uk-icon-youtube-square", "uk-icon-youtube", "uk-icon-xing", "uk-icon-xing-square", "uk-icon-youtube-play", "uk-icon-dropbox", "uk-icon-stack-overflow", "uk-icon-instagram", "uk-icon-flickr", "uk-icon-adn", "uk-icon-bitbucket", "uk-icon-bitbucket-square", "uk-icon-tumblr", "uk-icon-tumblr-square", "uk-icon-long-arrow-down", "uk-icon-long-arrow-up", "uk-icon-long-arrow-left", "uk-icon-long-arrow-right",
    "uk-icon-apple", "uk-icon-windows", "uk-icon-android", "uk-icon-linux", "uk-icon-dribbble", "uk-icon-skype", "uk-icon-foursquare", "uk-icon-trello", "uk-icon-female", "uk-icon-male", "uk-icon-gittip", "uk-icon-gratipay", "uk-icon-sun-o", "uk-icon-moon-o", "uk-icon-archive", "uk-icon-bug", "uk-icon-vk", "uk-icon-weibo", "uk-icon-renren", "uk-icon-pagelines",
    "uk-icon-stack-exchange", "uk-icon-arrow-circle-o-right", "uk-icon-arrow-circle-o-left", "uk-icon-caret-square-o-left", "uk-icon-toggle-left", "uk-icon-dot-circle-o", "uk-icon-wheelchair", "uk-icon-vimeo-square", "uk-icon-try", "uk-icon-turkish-lira", "uk-icon-plus-square-o", "uk-icon-space-shuttle", "uk-icon-slack", "uk-icon-envelope-square", "uk-icon-wordpress", "uk-icon-openid", "uk-icon-bank", "uk-icon-institution", "uk-icon-university", "uk-icon-graduation-cap",
    "uk-icon-mortar-board", "uk-icon-yahoo", "uk-icon-google", "uk-icon-reddit", "uk-icon-reddit-square", "uk-icon-stumbleupon-circle", "uk-icon-stumbleupon", "uk-icon-delicious", "uk-icon-digg", "uk-icon-pied-piper", "uk-icon-pied-piper-alt", "uk-icon-drupal", "uk-icon-joomla", "uk-icon-language", "uk-icon-fax", "uk-icon-building", "uk-icon-child", "uk-icon-paw", "uk-icon-spoon", "uk-icon-cube",
    "uk-icon-cubes", "uk-icon-behance", "uk-icon-behance-square", "uk-icon-steam", "uk-icon-steam-square", "uk-icon-recycle", "uk-icon-automobile", "uk-icon-car", "uk-icon-cab", "uk-icon-taxi", "uk-icon-tree", "uk-icon-spotify", "uk-icon-deviantart", "uk-icon-soundcloud", "uk-icon-database", "uk-icon-file-pdf-o", "uk-icon-file-word-o", "uk-icon-file-excel-o", "uk-icon-file-powerpoint-o", "uk-icon-file-image-o",
    "uk-icon-file-photo-o", "uk-icon-file-picture-o", "uk-icon-file-archive-o", "uk-icon-file-zip-o", "uk-icon-file-audio-o", "uk-icon-file-sound-o", "uk-icon-file-movie-o", "uk-icon-file-video-o", "uk-icon-file-code-o", "uk-icon-vine", "uk-icon-codepen", "uk-icon-jsfiddle", "uk-icon-life-bouy", "uk-icon-life-buoy", "uk-icon-life-ring", "uk-icon-life-saver", "uk-icon-support", "uk-icon-circle-o-notch", "uk-icon-ra", "uk-icon-rebel",
    "uk-icon-empire", "uk-icon-ge", "uk-icon-git-square", "uk-icon-git", "uk-icon-hacker-news", "uk-icon-tencent-weibo", "uk-icon-qq", "uk-icon-wechat", "uk-icon-weixin", "uk-icon-paper-plane", "uk-icon-send", "uk-icon-paper-plane-o", "uk-icon-send-o", "uk-icon-history", "uk-icon-circle-thin", "uk-icon-genderless", "uk-icon-header", "uk-icon-paragraph", "uk-icon-sliders", "uk-icon-share-alt",
    "uk-icon-share-alt-square", "uk-icon-bomb", "uk-icon-futbol-o", "uk-icon-soccer-ball-o", "uk-icon-tty", "uk-icon-binoculars", "uk-icon-plug", "uk-icon-slideshare", "uk-icon-twitch", "uk-icon-yelp", "uk-icon-newspaper-o", "uk-icon-wifi", "uk-icon-calculator", "uk-icon-paypal", "uk-icon-google-wallet", "uk-icon-cc-visa", "uk-icon-cc-mastercard", "uk-icon-cc-discover", "uk-icon-cc-amex", "uk-icon-cc-paypal",
    "uk-icon-cc-stripe", "uk-icon-bell-slash", "uk-icon-bell-slash-o", "uk-icon-trash", "uk-icon-copyright", "uk-icon-at", "uk-icon-eyedropper", "uk-icon-paint-brush", "uk-icon-birthday-cake", "uk-icon-area-chart", "uk-icon-pie-chart", "uk-icon-line-chart", "uk-icon-lastfm", "uk-icon-lastfm-square", "uk-icon-toggle-off", "uk-icon-toggle-on", "uk-icon-bicycle", "uk-icon-bus", "uk-icon-ioxhost", "uk-icon-angellist",
    "uk-icon-cc", "uk-icon-ils", "uk-icon-shekel", "uk-icon-sheqel", "uk-icon-meanpath", "uk-icon-buysellads", "uk-icon-connectdevelop", "uk-icon-dashcube", "uk-icon-forumbee", "uk-icon-leanpub", "uk-icon-sellsy", "uk-icon-shirtsinbulk", "uk-icon-simplybuilt", "uk-icon-skyatlas", "uk-icon-cart-plus", "uk-icon-cart-arrow-down", "uk-icon-diamond", "uk-icon-ship", "uk-icon-user-secret", "uk-icon-motorcycle",
    "uk-icon-street-view", "uk-icon-heartbeat", "uk-icon-venus", "uk-icon-mars", "uk-icon-mercury", "uk-icon-transgender", "uk-icon-transgender-alt", "uk-icon-venus-double", "uk-icon-mars-double", "uk-icon-venus-mars", "uk-icon-mars-stroke", "uk-icon-mars-stroke-v", "uk-icon-mars-stroke-h", "uk-icon-neuter", "uk-icon-facebook-official", "uk-icon-pinterest-p", "uk-icon-whatsapp", "uk-icon-server", "uk-icon-user-plus", "uk-icon-user-times",
    "uk-icon-bed", "uk-icon-hotel", "uk-icon-viacoin", "uk-icon-train", "uk-icon-subway", "uk-icon-medium-logo", "uk-close", "uk-close-alt", "uk-badge", "uk-badge-notification", "uk-badge-success", "uk-badge-warning", "uk-badge-danger", "uk-alert", "uk-alert-success", "uk-alert-warning", "uk-alert-danger", "uk-alert-large", "uk-thumbnail", "uk-thumbnail-caption",
    "uk-thumbnail-mini", "uk-thumbnail-small", "uk-thumbnail-medium", "uk-thumbnail-large", "uk-thumbnail-expand", "uk-overlay", "uk-border-circle", "uk-overlay-panel", "uk-flex", "uk-overlay-active", "uk-ignore", "uk-overlay-hover", "uk-hover", "uk-overlay-background", "uk-overlay-top", "uk-overlay-bottom", "uk-overlay-left", "uk-overlay-right", "uk-overlay-icon", "uk-overlay-blur",
    "uk-overlay-fade", "uk-overlay-grayscale", "uk-overlay-scale", "uk-overlay-spin", "uk-overlay-slide-top", "uk-overlay-slide-bottom", "uk-overlay-slide-left", "uk-overlay-slide-right", "uk-overlay-area", "uk-overlay-toggle", "uk-overlay-area-content", "uk-overlay-caption", "uk-progress", "uk-progress-bar", "uk-progress-mini", "uk-progress-small", "uk-progress-success", "uk-progress-warning", "uk-progress-danger", "uk-progress-striped",
    "uk-animation-fade", "uk-animation-scale-up", "uk-animation-scale-down", "uk-animation-slide-top", "uk-animation-slide-bottom", "uk-animation-slide-left", "uk-animation-slide-right", "uk-animation-scale", "uk-animation-shake", "uk-animation-reverse", "uk-animation-15", "uk-animation-top-left", "uk-animation-top-center", "uk-animation-top-right", "uk-animation-middle-left", "uk-animation-middle-right", "uk-animation-bottom-left", "uk-animation-bottom-center", "uk-animation-bottom-right", "uk-animation-hover",
    "uk-dropdown", "uk-dropdown-flip", "uk-dropdown-up", "uk-dropdown-grid", "uk-dropdown-stack", "uk-dropdown-width-2", "uk-dropdown-width-3", "uk-dropdown-width-4", "uk-dropdown-width-5", "uk-dropdown-small", "uk-dropdown-navbar", "uk-dropdown-scrollable", "uk-modal", "uk-modal-page", "uk-modal-dialog", "uk-modal-dialog-lightbox", "uk-modal-dialog-large", "uk-modal-header", "uk-modal-footer", "uk-modal-caption",
    "uk-modal-spinner", "uk-offcanvas", "uk-offcanvas-page", "uk-offcanvas-bar", "uk-offcanvas-bar-show", "uk-offcanvas-bar-flip", "uk-switcher", "uk-tooltip", "uk-tooltip-top-left", "uk-tooltip-top-right", "uk-tooltip-top", "uk-tooltip-bottom-left", "uk-tooltip-bottom-right", "uk-tooltip-bottom", "uk-tooltip-left", "uk-tooltip-right", "uk-text-small", "uk-text-large", "uk-text-bold", "uk-text-muted",
    "uk-text-primary", "uk-text-success", "uk-text-warning", "uk-text-danger", "uk-text-contrast", "uk-text-left", "uk-text-right", "uk-text-center", "uk-text-justify", "uk-text-top", "uk-text-middle", "uk-text-bottom", "uk-text-center-medium", "uk-text-left-medium", "uk-text-center-small", "uk-text-left-small", "uk-text-nowrap", "uk-text-truncate", "uk-text-break", "uk-container",
    "uk-container-center", "uk-clearfix", "uk-nbfc", "uk-nbfc-alt", "uk-float-left", "uk-float-right", "uk-align-left", "uk-align-right", "uk-align-medium-left", "uk-align-medium-right", "uk-align-center", "uk-vertical-align", "uk-vertical-align-bottom", "uk-vertical-align-middle", "uk-height-1-1", "uk-height-viewport", "uk-responsive-height", "uk-responsive-width", "uk-margin", "uk-margin-top",
    "uk-margin-bottom", "uk-margin-left", "uk-margin-right", "uk-margin-large", "uk-margin-large-top", "uk-margin-large-bottom", "uk-margin-large-left", "uk-margin-large-right", "uk-margin-small", "uk-margin-small-top", "uk-margin-small-bottom", "uk-margin-small-left", "uk-margin-small-right", "uk-margin-remove", "uk-margin-top-remove", "uk-margin-bottom-remove", "uk-border-rounded", "uk-heading-large", "uk-link-muted", "uk-link-reset",
    "uk-scrollable-text", "uk-scrollable-box", "uk-overflow-container", "uk-position-top", "uk-position-bottom", "uk-position-top-left", "uk-position-top-right", "uk-position-bottom-left", "uk-position-bottom-right", "uk-position-cover", "uk-position-relative", "uk-display-block", "uk-display-inline", "uk-display-inline-block", "uk-hidden-large", "uk-visible-medium", "uk-visible-small", "uk-hidden-medium", "uk-visible-large", "uk-hidden-small",
    "uk-hidden", "uk-invisible", "uk-visible-hover", "uk-visible-hover-inline", "uk-notouch", "uk-hidden-notouch", "uk-hidden-touch", "uk-flex-inline", "uk-flex-top", "uk-flex-middle", "uk-flex-bottom", "uk-flex-center", "uk-flex-right", "uk-flex-space-between", "uk-flex-space-around", "uk-flex-row-reverse", "uk-flex-column", "uk-flex-column-reverse", "uk-flex-wrap", "uk-flex-wrap-reverse",
    "uk-flex-wrap-top", "uk-flex-wrap-middle", "uk-flex-wrap-bottom", "uk-flex-wrap-space-between", "uk-flex-wrap-space-around", "uk-flex-order-first", "uk-flex-order-last", "uk-flex-order-first-small", "uk-flex-order-last-small", "uk-flex-order-first-medium", "uk-flex-order-last-medium", "uk-flex-order-first-large", "uk-flex-order-last-large", "uk-flex-order-first-xlarge", "uk-flex-order-last-xlarge", "uk-flex-item-none", "uk-flex-item-auto", "uk-flex-item-1", "uk-accordion-title", "uk-accordion-content",
    "uk-autocomplete", "uk-nav-autocomplete", "uk-datepicker", "uk-datepicker-nav", "uk-datepicker-previous", "uk-datepicker-next", "uk-datepicker-table", "uk-datepicker-table-muted", "uk-dotnav", "uk-dotnav-contrast", "uk-dotnav-vertical", "uk-form-file", "uk-form-password", "uk-form-password-toggle", "uk-form-select", "uk-htmleditor-navbar", "uk-htmleditor-navbar-nav", "uk-htmleditor-navbar-flip", "uk-htmleditor-button-code", "uk-htmleditor-button-preview",
    "uk-htmleditor-content", "uk-htmleditor-fullscreen", "uk-htmleditor-code", "uk-htmleditor-preview", "uk-htmleditor-iframe", "uk-htmleditor", "uk-nestable", "uk-nestable-list", "uk-nestable-list-dragged", "uk-nestable-item", "uk-nestable-placeholder", "uk-nestable-empty", "uk-nestable-handle", "uk-nestable-moving", "uk-collapsed", "uk-notify", "uk-notify-bottom-right", "uk-notify-top-right", "uk-notify-bottom-center", "uk-notify-top-center",
    "uk-notify-bottom-left", "uk-notify-message", "uk-notify-message-primary", "uk-notify-message-success", "uk-notify-message-warning", "uk-notify-message-danger", "uk-placeholder", "uk-placeholder-large", "uk-search", "uk-search-field", "uk-dropdown-search", "uk-nav-search", "uk-slidenav", "uk-slidenav-previous", "uk-slidenav-next", "uk-slidenav-position", "uk-slidenav-contrast", "uk-slideshow", "uk-slideshow-fullscreen", "uk-slideshow-fade-out",
    "uk-slideshow-scroll-forward-in", "uk-slideshow-scroll-forward-out", "uk-slideshow-scroll-backward-in", "uk-slideshow-scroll-backward-out", "uk-slideshow-scale-out", "uk-slideshow-swipe-forward-in", "uk-slideshow-swipe-forward-out", "uk-slideshow-swipe-backward-in", "uk-slideshow-swipe-backward-out", "uk-sortable", "uk-sortable-dragged", "uk-sortable-placeholder", "uk-sortable-over", "uk-sortable-moving", "uk-dragover"]

uikit_data = ["data-uk-margin", "data-uk-grid-match", "data-uk-grid-margin", "data-uk-check-display", "data-uk-observe", "data-uk-smooth-scroll", "data-uk-scrollspy", "data-uk-scrollspy-nav", "data-uk-toggle", "data-uk-alert", "data-uk-button-radio", "data-uk-button-checkbox", "data-uk-button", "data-uk-dropdown", "data-uk-modal", "data-uk-nav", "data-uk-offcanvas", "data-uk-switcher", "data-uk-switcher-item", "data-uk-tab", "data-uk-cover",
    "data-uk-tooltip", "data-uk-accordion", "data-uk-autocomplete", "data-uk-datepicker", "data-uk-form-password", "data-uk-form-select", "data-uk-grid", "data-uk-filter", "data-uk-sort", "data-uk-htmleditor", "data-uk-lightbox", "data-uk-nestable", "data-uk-pagination", "data-uk-search", "data-uk-slideshow", "data-uk-slideshow-item", "data-uk-sortable", "data-uk-sticky", "data-uk-timepicker"]

class UIkitCompletions(sublime_plugin.EventListener):
    """
    Provide tag completions for UIkit elements and data-uk attributes
    """
    def __init__(self):
        self.class_completions = [("%s \tUIkit class" % s, s) for s in uikit_classes]
        self.data_completions = [("%s \t UIkit uk-data" % s, "%s=\"$1\"" % s) for s in uikit_data]

    def on_query_completions(self, view, prefix, locations):
        if view.match_selector(locations[0], "text.html string.quoted"):
            # in attribute: attr="{here}"
            # make sure it only triggers when: class="{here}"
            pt = locations[0] - len(prefix) - 1
            SEARCH_LIMIT = 250
            search_start = max(0, pt - SEARCH_LIMIT - len(prefix))
            line = view.substr(sublime.Region(search_start, pt))
            parts = line.split('=')
            if len(parts) > 2 and parts[-2].strip().endswith("class"):
                return self.class_completions
            else:
                return []
        elif view.match_selector(locations[0], "text.html meta.tag - text.html punctuation.definition.tag.begin"):
            # in tag: <div {here}>
            return self.data_completions
        else:
            return []
